baseURL = "https://falco.org"
title = "The Falco Project"

theme = ["docsy"]

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
disableBrowserError = true

disableKinds = ["taxonomy", "taxonomyTerm"]

ignoreFiles = [ "^OWNERS$", "README[-]+[a-z]*\\.md", "^node_modules$", "content/en/docs/doc-contributor-tools" ]

timeout = 3000

# Highlighting config.
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "emacs"

# Enable Git variables like commit, lastmod
enableGitInfo = true

[caches]
 [caches.assets]
  dir = ":cacheDir/_gen"
  maxAge = -1
 [caches.getcsv]
  dir = ":cacheDir/:project"
  maxAge = "60s"
 [caches.getjson]
  dir = ":cacheDir/:project"
  maxAge = "60s"
 [caches.images]
  dir = ":cacheDir/_images"
  maxAge = -1
 [caches.modules]
  dir = ":cacheDir/modules"
  maxAge = -1

[markup]
 [markup.goldmark]
   [markup.goldmark.extensions]
     definitionList = true
     table = true
     typographer = false
   [markup.goldmark.parser]
     attribute = true
     autoHeadingID = true
     autoHeadingIDType = "blackfriday"
   [markup.goldmark.renderer]
     unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "emacs"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[frontmatter]
date = ["date", ":filename", "publishDate", "lastmod"]

[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[sitemap]
  filename = "sitemap.xml"
  priority = 0.75

# Be explicit about the output formats. We (currently) only want an RSS feed for the home page.
[outputs]
home = [ "HTML", "RSS", "HEADERS" ]
page = [ "HTML"]
section = [ "HTML"]

# Add a "text/netlify" media type for auto-generating the _headers file
[mediaTypes]
[mediaTypes."text/netlify"]
delimiter = ""

[outputFormats]
[outputFormats.RSS]
baseName = "feed"

# _headers file output (uses the template at layouts/index.headers)
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "UA-00000000-0"

# Additional menu items

[[menu.main]]
    name = "Documentation"
    weight = 40
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = 50
    url = "/blog/"



# Language configuration


# Everything below this are Site Params

[params]
copyright = "The Falco Authors"
copyright_linux =  "Copyright © 2020 The Linux Foundation ®."
privacy_policy = "https://policies.google.com/privacy"

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the
# current doc set.
version = "0.26.2"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://falco.org"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/falcosecurity/falco-website"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/falcosecurity/falco-website"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = "userguide"

time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
# Sections to publish in the main RSS feed.
rss_sections = ["blog"]

# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "011217106833237091527:la2vtv2emlw"

# Enable Algolia DocSearch
algolia_docsearch = false

#Enable offline search with Lunr.js
offlineSearch = false
offlineSearchSummaryLength = 70
offlineSearchMaxResults = 10

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = false

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
# Update with your own repository and response text.
yes = 'Glad to hear it! Please <a href="https://github.com/falcosecurity/falco-website/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/falcosecurity/falco-website/issues/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page,
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
 [[params.links.user]]
	name = "User mailing list"
	url = "https://discuss.kubernetes.io/"
	icon = "fa fa-envelope"
        desc = "Discussion and help from your fellow users"
[[params.links.user]]
	name ="Twitter"
	url = "https://twitter.com/falco_org"
	icon = "fab fa-twitter"
        desc = "Follow us on Twitter to get the latest news!"
[[params.links.user]]
	name = "Stack Overflow"
	url = "https://stackoverflow.com/questions/tagged/falco"
	icon = "fab fa-stack-overflow"
        desc = "Practical questions and curated answers"
[[params.links.user]]
	name = "Calendar"
	url = "https://lists.cncf.io/g/cncf-falco-dev/ics/4188901/1750099167/feed.ics"
	icon = "fas fa-calendar-alt"
        desc = "Subscribe to the Falco calendar, through this ics feed"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/falcosecurity/falco"
	icon = "fab fa-github"
        desc = "Development takes place here!"
[[params.links.developer]]
	name = "Slack"
	url = "https://slack.k8s.io"
	icon = "fab fa-slack"
        desc = "Chat with other project developers"
[[params.links.developer]]
	# name = "Developer mailing list"
	# url = "https://lists.cncf.io/g/cncf-falco-dev"
	# icon = "fa fa-envelope"
        # desc = "Discuss development issues around the project"

[params.mermaid]
enable = true
theme = "default"

[params.print]
disable_toc = false

# Language definitions.

[languages]
[languages.en]
title = "Falco"
description = "Runtime Security "
languageName ="English"
# Weight used for sorting.
weight = 1
languagedirection = "ltr"

[languages.zh]
title = "Falco"
description = "运行时安全"
languageName = "中文 Chinese"
weight = 2
contentDir = "content/zh"
languagedirection = "ltr"

[languages.zh.params]
time_format_blog = "2006.01.02"
language_alternatives = ["en"]


[languages.ko]
title = "Falco"
description = "런타임 보안"
languageName = "한국어 Korean"
weight = 3
contentDir = "content/ko"
languagedirection = "ltr"

[languages.ko.params]
time_format_blog = "2006.01.02"
language_alternatives = ["en"]

[languages.ja]
title = "Falco"
description = "ランタイムセキュリティ"
languageName = "日本語 Japanese"
weight = 4
contentDir = "content/ja"
languagedirection = "ltr"

[languages.ja.params]
time_format_blog = "2006.01.02"
language_alternatives = ["en"]

[[params.versions]]
fullversion = "v0.26.2"
version = "v0.26.2"
githubbranch = "v0.26.2"
docsbranch = "master"
url = "https://falco.org"

[[params.versions]]
fullversion = "v0.26.3"
version = "v0.26.3"
githubbranch = "v0.26.3"
docsbranch = "master"
url = "https://falco.org/v3"
