---
# Flag used in the "version-banner" partial to decide whether to display a
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.

archived_version: false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the
# current doc set.

version: v0.39.2

# The version of the default rules set
# Keep it aligned with the version of Falco for compatibility
rulesversion: 3.0.0

# The archived versions of the docs available for reference.
# Used in the Releases menu, as well as in the Available Documentation Versions

versions:
  - fullversion: v0.39.2
    version: v0.39
    githubbranch: master
    docsbranch: master
    url: https://falco.org/

  - fullversion: v0.38.2
    version: v0.38
    githubbranch: 0.38.2
    docsbranch: v0.38
    url: https://v0-38.falco.org/

  - fullversion: v0.37.1
    version: v0.37
    githubbranch: 0.37.1
    docsbranch: v0.37
    url: https://v0-37.falco.org/

  - fullversion: v0.36.2
    version: v0.36
    githubbranch: 0.36.2
    docsbranch: v0.36
    url: https://v0-36.falco.org/

  - fullversion: v0.35.1
    version: v0.35
    githubbranch: 0.35.1
    docsbranch: v0.35
    url: https://v0-35.falco.org/
        
  - fullversion: v0.34.1
    version: v0.34
    githubbranch: 0.34.1
    docsbranch: v0.34
    url: https://v0-34.falco.org/

  - fullversion: v0.33.1
    version: v0.33
    githubbranch: 0.33.1
    docsbranch: v0.33
    url: https://v0-33.falco.org/

  - fullversion: v0.32.2
    version: v0.32
    githubbranch: 0.32.2
    docsbranch: v0.32
    url: https://v0-32.falco.org/

  - fullversion: v0.31.1
    version: v0.31
    githubbranch: 0.31.1
    docsbranch: v0.31
    url: https://v0-31.falco.org/

  - fullversion: v0.30.0
    version: v0.30
    githubbranch: 0.30.0
    docsbranch: v0.30
    url: https://v0-30.falco.org/

  - fullversion: v0.29.1
    version: v0.29
    githubbranch: 0.29.1
    docsbranch: v0.29
    url: https://v0-29.falco.org/

  - fullversion: v0.28.1
    version: v0.28
    githubbranch: 0.28.1
    docsbranch: v0.28
    url: https://v0-28.falco.org/

  - fullversion: v0.27.0
    version: v0.27
    githubbranch: 0.27.0
    docsbranch: v0.27
    url: https://v0-27.falco.org/

  - fullversion: v0.26.2
    version: v0.26
    githubbranch: 0.26.2
    docsbranch: v0.26
    url: https://v0-26.falco.org/
