# Language definitions.

en:
  title: "Falco"
  languageName: "English"
  # Weight used for sorting.
  weight: 1
  languagedirection: "ltr"
  params:
    description: "Runtime Security"

zh-cn:
  title: "Falco"
  languageName: "中文 Chinese"
  weight: 2
  contentDir: "content/zh-cn"
  languagedirection: "ltr"
  params:
    time_format_blog: "2006.01.02"
    language_alternatives: ["en"]
    description: "运行时安全"

ko:
  title: "Falco"
  languageName: "한국어 Korean"
  weight: 3
  contentDir: "content/ko"
  languagedirection: "ltr"
  params:
    time_format_blog: "2006.01.02"
    language_alternatives: ["en"]
    description: "런타임 보안"

ja:
  title: "Falco"
  languageName: "日本語 Japanese"
  weight: 4
  contentDir: "content/ja"
  languagedirection: "ltr"
  params:
    time_format_blog: "2006.01.02"
    language_alternatives: ["en"]
    description: "ランタイムセキュリティ"

ml:
  title: "Falco"
  languageName: "മലയാളം Malayalam"
  weight: 4
  contentDir: "content/ml"
  languagedirection: "ltr"
  params:
    time_format_blog: "2006.01.02"
    language_alternatives: ["en"]
    description: "റൺടൈം സെക്യൂരിറ്റി"
