mounts:
  - source: 'content/en'
    target: 'content'
    lang: 'en'
  - source: 'content/zh-cn'
    target: 'content'
    lang: 'zh-cn'
  - source: 'content/ko'
    target: 'content'
    lang: 'ko'
  - source: 'content/ja'
    target: 'content'
    lang: 'ja'
  - source: 'content/ml'
    target: 'content'
    lang: 'ml'
  - source: 'content/en'
    target: 'content'
    excludeFiles: 'blog/*'
    lang: 'zh-cn'
  - source: 'content/en'
    target: 'content'
    excludeFiles: 'blog/*'
    lang: 'ko'
  - source: 'content/en'
    target: 'content'
    excludeFiles: 'blog/*'
    lang: 'ja'
  - source: 'content/en'
    target: 'content'
    excludeFiles: 'blog/*'
    lang: 'ml'
